### PR TITLE
Moved opening braces to next line for class definitions

### PR DESCRIPTION
**Pull request by jmrocela**
PSR-2

### CODE REVIEW

**Comment by natzim** [comment]
The [contribution style guide](http://laravel.com/docs/5.0/contributions#coding-style) states:

> A class' opening { must be on the same line as the class name.

**Comment by GrahamCampbell** [comment]
Yes. We will be fixing this ourselves soon. :)

**Comment by natzim** [comment]
So what is the standard for contributing to Lumen? The base controller class has the opening brace on a new line, but the rest of the classes have it on the same line.

**Comment by GrahamCampbell** [comment]
> So what is the standard for contributing to Lumen? The base controller class has the opening brace on a new line, but the rest of the classes have it on the same line.

PSR-2. We just are not accepting changes to fix it. We will deal with it at some point soon.

**Pull request closed without merging**
