### PR TITLE
Remove check for Hello World

### PR DESCRIPTION
**Pull request by mhanson01**
There is no "Hello World" page on the default install, just displays "Lumen." So we should just be able to assert that the response is OK to get green on a default install, similar the default test on laravel/laravel.

### CODE REVIEW

**Comment by limonte** [comment]
Instead of removing that line you can change it to

```php
$this->assertEquals('Lumen.', $response->getContent());
```

**Comment by mhanson01** [comment]
getContents() will pull back the full HTML source, so we'd do the following to see if "Lumen." is there, right?

```php
$this->assertContains('Lumen.', $response->getContent());

**Comment by limonte** [comment]
you're right. May be ``assertViewHas()`` will work here.

**Comment by jasonvarga** [comment]
What about this?

```
$this->assertEquals($this->app->welcome(), $response->getContent());
```

**Comment by mhanson01** [comment]
@jasonvarga IMO, that definitely looks like a really good option to replace the current "Hello World" check. If the welcome page changes in the future, the test should still pass with this comparison.  I like it!

**Pull request merged**
