### PR TITLE
Trailing slashes directory condition

### PR DESCRIPTION
**Pull request by verheesj**
Add rewrite condition to the trailing slashes rewrite due to a redirect loop occurring when making a request to a public directory.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
:+1:

**Comment by GrahamCampbell** [comment]
Same as https://github.com/laravel/laravel/commit/dd036f559b3213279e4dfa8ab055aeac3dab2521.

**Comment by GrahamCampbell** [comment]
Maybe we need to update the comment to match?

**Comment by GrahamCampbell** [comment]
https://github.com/laravel/laravel/commit/804b9d746078482ee4e644d680bd87ca4e47b003

**Comment by GrahamCampbell** [comment]
https://github.com/laravel/laravel/commit/804b9d746078482ee4e644d680bd87ca4e47b003

**Comment by verheesj** [comment]
@GrahamCampbell wording fixed

**Pull request merged**
