### PR TITLE
Update index.php

### PR DESCRIPTION
**Pull request by mathewhany**

### CODE REVIEW

**Comment by lukasgeiter** [comment]
The same thing has already been rejected: #4

**Comment by micfai** [comment]
@taylorotwell I understand from reading #4 that it is intentional but can you give more context as to why it was intentional?

**Comment by lukasgeiter** [comment]
@micfai Performance. Lumens routing ([nikic/FastRoute](https://github.com/nikic/FastRoute)) works with just an URI string and there's no need to create the full Symfony Request.

**Comment by micfai** [comment]
@lukasgeiter I figured it was for performance gain. It doesn't solve the issue for people attempting to run Lumen in a sub-directory though (don't know why you would, friend is attempting to anyways) which is where this pull fixes it for them.

Any ideas on another way to solve this issue and keep the performance benefits?

**Comment by lukasgeiter** [comment]
@micfai Yes, my own PR: laravel/lumen-framework#35 would fix that.
Unfortunately Taylor didn't like it too much...

**Comment by micfai** [comment]
@lukasgeiter Thanks for the info. I hadn't checked the framework pull requests yet.

**Pull request closed without merging**
