### PR TITLE
Error first load Lumen

### PR DESCRIPTION
**Pull request by Talean-dev**
Example question and error: http://stackoverflow.com/questions/29728973/notfoundhttpexception-with-lumen

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
This is a duplicate. We do this on purpose in the interest of performance.

**Comment by Talean-dev** [comment]
How to understand it. Why is that?
The finished product should work fine

**Comment by limonte** [comment]
@Talean-dev to understand read duplicate PRs, e.g. https://github.com/laravel/lumen/pull/18

**Comment by Talean-dev** [comment]
thanks

**Pull request closed without merging**
