### PR TITLE
Only one pair of commas neccessary

### PR DESCRIPTION
**Pull request by rweas**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
This is intentional so you can uncomment the whole thing, and still have each middleware commented out.

**Comment by rweas** [comment]
Oh I see.

**Comment by lukasgeiter** [comment]
@GrahamCampbell Then why not use a multi-line comment for the whole block?

**Comment by ganey** [comment]
To add the middleware one by one, rather than move the start tag around and then have to add in your own comment tags for each middleware item?

**Comment by lukasgeiter** [comment]
What I suggest is this:

    /* $app->middleware([
        // 'Illuminate\Cookie\Middleware\EncryptCookies',
        // 'Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse',
        // 'Illuminate\Session\Middleware\StartSession',
        // 'Illuminate\View\Middleware\ShareErrorsFromSession',
        // 'Laravel\Lumen\Http\Middleware\VerifyCsrfToken',
    ]); */

**Comment by rweas** [comment]
It's faster to use single line. I can just hit cmd+/ to enable it.

**Comment by lukasgeiter** [comment]
@rweas That depends on what editor you are using. *(I don't really care that much, so I'm totally okay if we just leave it like it is)*

**Comment by andrewhood125** [comment]
:+1: for leaving it the way it is.

**Pull request closed without merging**
