### PR TITLE
Add DB_PREFIX and S3_URL to .env.example

### PR DESCRIPTION
**Pull request by andrewhood125**
PR #19 on lumen-framework introduced DB_PREFIX.
PR #14 on lumen-framework introduced S3_URL

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Lumen will ship with the bare minimum. People can easily add this by looking at laravel.

**Comment by andrewhood125** [comment]
I understand that Lumen is meant to be bare bones and very fast. However this does not affect performance at all. I would say it increases user experience. 

The DB_PREFIX and S3_URL options are not in Laravel's `.env.example` either. 

https://github.com/laravel/laravel/blob/master/.env.example

**Comment by andrewhood125** [comment]
Thanks for the explanation though.

**Comment by GrahamCampbell** [comment]
No, I'm not talking about speed. I'm saying we want our default app structure to be minimal.

**Pull request closed without merging**
