### PR TITLE
Adding a MAIL_ENCRYPTION default value.

### PR DESCRIPTION
**Pull request by bobsta63**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
?

**Comment by GrahamCampbell** [comment]
Surely this is a bad default?

**Comment by bobsta63** [comment]
It is currently the default on the Laravel .env.example file (
https://github.com/laravel/laravel/blob/master/.env.example)... So why
shouldn't it be for Lumen too?

In my opinion I'd only really ever use the default .env.example for a
development environment anyway, when the application goes into production
I'd be vetting my production .env file throughly.

**Comment by bobsta63** [comment]
I don't mean to troll but just wondered why this was just closed without
merging especially as it is the same for Laravel and considering that most
local development SMTP servers don't support TLS etc. (eg. MailCatcher and
MailHog).

Makes me wonder if I'm not understanding something/being an idiot??

**Pull request closed without merging**
